name: GitHub Pages

on:
  push:
    branches:
      - master

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    # environment:
    #   name: github-pages
    #   url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder:
          - ./USACM_2024
          - ./PDDAY_2024
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npm ci

      - name: Build Marp slide deck'{{ matrix.folder }}'
        run: CHROME_PATH=$(npx -y @puppeteer/browsers@latest install chrome@stable --path $(realpath ./tmp) | awk '{print $2}') FOLDER=${{ matrix.folder }} npm run build
        env:
          # Please update URL if you want to use custom domain
          URL: https://${{ github.event.repository.owner.name }}.github.io/${{ github.event.repository.name }}/${{ matrix.folder }}

      - name: Deploy to GitHub Pages for '{{ matrix.folder }}'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ matrix.folder }}_public
          destination_dir: ${{ matrix.folder }}
