name: GitHub Pages

on:
  push:
    branches:
      - master

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  # prepare:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Install Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         cache: npm
  #         node-version-file: ".nvmrc"

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Copy assets
  #       run: npm copy

  build:
    # needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder:
          - USACM_2024
          - PDDAY_2024
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npm ci

      # - name: Copy assets
      #   run: npm run copy
      - name: Build Marp slide deck
        run: CHROME_PATH=$(npx -y @puppeteer/browsers@latest install chrome@stable --path $(realpath ./tmp) | awk '{print $2}') FOLDER=${{ matrix.folder }} npm run build
        # env:
        # Please update URL if you want to use custom domain
        # URL: https://${{ github.event.repository.owner.name }}.github.io/${{ github.event.repository.name }}/${{ matrix.folder }}

      - name: Upload page artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/${{ matrix.folder }}
          name: ${{ matrix.folder }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download page artifacts
        uses: actions/download-artifact@v4
        with:
          path: public
          merge-multiple: true

      - name: Copy assets
        run: npm run copy

      - name: Upload page artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
