name: GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - "**.md"

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npm ci

      - name: Cache node_modules folder
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder:
          - COMPLAS_2025
          - Antrittsvorlesung
          - GAMM_2024
          - GAMM_2026
          - USACM_2024
          - PDDAY_2024
          - PDDAY_2025
          - MICRO_ANALYSIS
    steps:
      - uses: actions/checkout@v4

      - name: Restore cached Primes
        uses: actions/cache/restore@v5
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Build Marp slide deck
        run: FOLDER=${{ matrix.folder }} npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: public
          name: ${{ matrix.folder }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download page artifacts
        uses: actions/download-artifact@v4
        with:
          path: public
          merge-multiple: true

      - name: Copy assets and index.html
        run: |
          cp -r presentations/assets public/assets
          cp index.html public/index.html

      - name: Upload page artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
